- name: Install nginx and start the service
  hosts: Web
  become: yes #become is equal to -b in adhoc commands it will run with root
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
     name: nginx
     state: latest
  - name: start the service
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes